drop table m_quest;
drop table a_quest_item;
drop table a_quest;
drop table z_utente;
drop table z_profilo;
drop table a_paziente;
drop table t_stato_civile;
drop table t_patologia;
drop table t_titolo;
